### ISSUE TITLE
FlightGear 2020 3.11 Error : FGPropertyValue when I run the MD80/82

### ISSUE THREAD

**Issue by pibol** [Octal450/MD-80#6]
Windows 10
FlightGear 2020 3.11
Plane MD80 Master
the file of MD80 is in the repertory /Data/Aircraft of Flightgear

When I run the MD 80/82 at the initialisation of the MD80 there is one error, sometimes not the same but often it is a message window :

"FGPropertyValue(): GetValue() the property / controls/lighthing/main-panel-knb  does not exist.
When I push 'Annuler' I go out of FlightGear.

I take FlightGear directly from the site FlightGear.
I fly with the Boeing 777-300, the Cessna 172P, there is not this error.

Bona dimenjada
Pibol

**Comment by Octal450** [comment]
There is no error. You are not installed the plane correctly. Go read INSTALL.md

Kind Regards,
Josh
